# Site settings
title: Zou Chenxuanyin
name: Zou Chenxuanyin
subtitle:  Economist
email: zcxy0218@gmail.com
description: >
   Engineer
baseurl: ""
url: "https://zcxy-academic.github.io/"
github_username:  zcxy-academic
disqus_baseurl: "https://zcxy-academic.github.io/"
disqus_shortname: https-zcxy-academic-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zou Chenxuanyin"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/zcxy-academic
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://www.linkedin.com/in/paul-e-soto-2705ab218
    desc: Connect with me on LinkedIn
    share: true
